name: Generate Contribution Snake
permissions:
  contents: write
  pages: write
  id-token: write
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate contribution snake SVG
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: vedantRaikar
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Publish dist to `output` branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          # prefer using a personal token when GITHUB_TOKEN actor lacks push permissions
          personal_token: ${{ secrets.GH_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
